### ISSUE TITLE
unable to resolve type URL /osmosis.gamm.v1beta1.MsgCreatePool

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#202]
I got this error

```
6:25PM ERR Failed to process block 2695938 after 5 attempts. Will add to failed blocks table
6:25PM ERR Error getting transactions by block height. Will reattempt error="rpc error: code = InvalidArgument desc = unable to resolve type URL /osmosis.gamm.v1beta1.MsgCreatePool: tx parse error: invalid request"
```
with this compose file.

```docker-compose.yml
version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  postgres:
    restart: "unless-stopped"
    image: postgres:15-alpine
    stop_grace_period: 1m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=taxuser
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432/tcp
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "localhost", "5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - defiant
    <<: *logging
  indexer:
    restart: "no"
    image: ghcr.io/defiantlabs/cosmos-tax-cli-private:sha-766a0e6
    user: defiant
    stop_grace_period: 1m
    volumes:
      # - indexer:/var/lib/cosmos-tax-cli-private-index
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      default:
        aliases:
          - defiant
    <<: *logging
    command:
    - /bin/sh
    - -c
    - |
      cosmos-tax-cli-private index \
      --log.pretty = true \
      --log.level = debug \
      --base.startBlock 2695938 \
      --base.endBlock 2695938 \
      --base.index true \
      --base.throttling 1.9 \
      --base.api https://api.osmosis.strange.love:443 \
      --lens.rpc http://104.196.107.57:26657 \
      --lens.accountPrefix osmo \
      --lens.keyringBackend test \
      --lens.chainID osmosis-1 \
      --lens.chainName osmosis \
      --db.host postgres \
      --db.database postgres \
      --db.user taxuser \
      --db.password password
```

**Comment by pharr117** [comment]
I have some experience with this one. If you follow the link [here](https://github.com/osmosis-labs/osmosis/issues/1017) that David pointed out above, you will see that the Osmosis devs have changed the name from MsgCreatePool -> MsgCreateBalancerPool.

What this does is break the chain's ability to decode old message types since type names are used in the process of decoding backend state to generate the proper message type.

Essentially, since Osmosis deprecated the old type, the current version of Osmosis will never be able to properly decode its own state to return to us. Since we use the current version of Osmosis in Lens to decode the messages, this breaks.

Either Osmosis will need to come to a conclusion to resolve this issue, or we will need to explore alternative methods of getting the message into the proper type.

**Comment by danbryan** [comment]
Can we import a map of osmosis versions to block-heights and make sure we are using the version that was used to create the block?

**Comment by KyleMoser** [comment]
In lens we just need to make a folder and put the old type in the folder.
Then register the type the same way all other types get registered (look at
ModuleBasics in lens to follow the flow)

**Comment by danbryan** [comment]
Chatted about this in the `3/8/23` sprint, has not been resumed yet

**Comment by danbryan** [comment]
march 15th,

@KyleMoser said 

```
I'm still figuring out if I implemented #202 correctly (trying to get csvs with it). Gotta compare the csv to Join pool ones I think
```

**Comment by KyleMoser** [comment]
The indexer is implemented correctly (I believe), but the CSV parser needs work still.

**Comment by danbryan** [comment]
@pharr117 mind checking if this one can be closed out?

**Comment by pharr117** [comment]
Just reran the indexer on this block and it succeeds, closing.
