### ISSUE TITLE
Update parsers to handle internal transfers

### ISSUE THREAD

**Issue by davidkonigsberg** [DefiantLabs/cosmos-tax-cli#237]
We will need to update ParseBasic for all the parsers to properly handle when funds are moved between multiple wallets controlled by the same user.

Ultimately, this will need to handle both:
- Same wallet address on multiple changes
- Different wallet addresses across same/multiple chains but all owned by the same user.

**Comment by danbryan** [comment]
cc @jtieri i think this will also be closed by your IBC transfer tickets.  Feel free to mark it as a dupe, or close it along side if you think this has special conditions worth keeping seperate
