### ISSUE TITLE
FTL Two queries for the same block (2965714) got a diff # of TXs

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#243]
Using this config, i consistently get the same error.
`FTL Two queries for the same block (2965714) got a diff # of TXs`

```
    [log]
    level = "info"
    pretty = true

    [base]
    addressRegex = "osmo(valoper)?1[a-z0-9]{38}"
    addressPrefix = "osmo"
    api = "http://osmosis-archive-1.nodes:1317"
    # startblock = 2612600
    startblock = 2965612
    endblock = 7444264
    RewardsStartBlock = 3104870
    throttling = 0.0005
    rpcworkers = 1
    blockTimer = 1000
    waitForChain = false
    preventReattempts = true
    waitForChainDelay = 1
    indexingEnabled = true
    exitWhenCaughtUp = false
    osmosisRewardsOnly = false
    RewardIndexingEnabled = true
    Dry = false

    [lens]
    # rpc = "http://osmosis-archive-1.nodes:26657"
    rpc = "http://osmosis-archive-1.nodes:26657"
    key = "default"
    accountPrefix = "osmo"
    keyringBackend = "test"
    chainID = "osmosis-1"
    chainName = "osmosis"
```

**Comment by esaari1** [comment]
@danbryan Looks like this is handled by David K in #254 with the alternate RPC. Can you look that over and see if what he did there will work?

**Comment by danbryan** [comment]
@esaari1 nope, that did not work, I am confident all osmosis nodes have the same "bad data" and having a backup RPC node is not the way to solve this.  Based on a conversation I had with @KyleMoser yesterday, we both agree that  the correct way to solve this is described in my comment above.  Would you like to sync with @KyleMoser and I and we can go over this in more detail tomorrow?

**Comment by esaari1** [comment]
I'm gonna make an attempt at this tomorrow, making a new function that will handle the second query. I'll let you know how it goes.

**Comment by esaari1** [comment]
GetBlockByHeight() does not seem to include transaction hashes with the returned data. I am guessing those hashes are rather important to this whole thing. I have tried to find another way to get them. Only other useful function was GetBlock(). This also returns a series of transactions, but here each transaction is just a raw byte array.  Not sure what (if anything) I can do there to get anything meaningful out of that. 

Anyone have any advice?
