### ISSUE TITLE
Initial Support for type '/cosmwasm.wasm.v1.MsgExecuteContract'.

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#246]
I want us to start researching how we can handle contract execution for the tax app.  I think Kujiras FINN is a good place to start. I'm not sure of all the contract involved, but 2 that i noticed are `Contract-Submit Order` and `Contract-Withdraw Orders` .   

-Block 7193280 is an example of  `Contract-Submit Order`
-Block 7193498 is an example of  `Contract-Withdraw Orders`

Kujiras Developer Docs: https://docs.kujira.app/developers/dapp-front-ends/fin

Here is a quick explanation of what FINN is: https://www.youtube.com/watch?v=0MHmxMWx-2w

Lets do a working session to start on this where i show you Kujiras Testnet, how you can create some order to see what happens on chain.  The big picture idea would be.  If I create an order to sell Kujira for Atom, it would show in the CSV that I sold Kujira and Bought Atom.

Here is the config.toml I used to generate this error.

```
    [base]
    addressRegex = "kujira(valoper)?1[a-z0-9]{38}"
    addressPrefix = "kujira"
    api = "https://lcd.kaiyo.kujira.setten.io:443"
    # startblock = 2612600
    startblock = 7193280
    endblock = 7193280
    RewardsStartBlock = 3078867
    throttling = 0.0005
    rpcworkers = 1
    blockTimer = 1000
    waitForChain = false
    reindex = true
    preventReattempts = true
    waitForChainDelay = 1
    indexingEnabled = true
    exitWhenCaughtUp = false
    osmosisRewardsOnly = false
    RewardIndexingEnabled = false
    Dry = false

    [lens]
    # rpc = "http://osmosis-archive-1.nodes:26657"
    rpc = "https://rpc.kaiyo.kujira.setten.io:443"
    key = "default"
    accountPrefix = "kujira"
    keyringBackend = "test"
    chainID = "kaiyo-1"
    chainName = "kujira"
```

**Comment by pharr117** [comment]
Closing this one out as the initial strategy is finished and documented at the repo wiki article [CosmWasm MsgExecuteContract Indexing Strategy ‐ Pre‐Development](https://github.com/DefiantLabs/cosmos-tax-cli/wiki/CosmWasm-MsgExecuteContract-Indexing-Strategy-%E2%80%90-Pre%E2%80%90Development)
