### ISSUE TITLE
3417163 - unable to resolve type URL /osmosis.gamm.v1beta1.MsgCreateBalancerPool

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#253]
Can you research if their is anything taxable to handle in this type, if not we can just handle the fees and add this to the list of ignored types.

Block `3417163`
Error:  `ERR Error getting transactions by block height (3417163). Err: rpc error: code = InvalidArgument desc = unable to resolve type URL /osmosis.gamm.v1beta1.MsgCreateBalancerPool: tx parse error: invalid request.
`
config.toml
```
    [base]
    addressRegex = "osmo(valoper)?1[a-z0-9]{38}"
    addressPrefix = "osmo"
    api = "http://osmosis-archive-1.nodes:1317"
    # startblock = 2612600
    startblock = 3417163
    endblock = 3417163
    RewardsStartBlock = 3417163
    throttling = 0.0005
    rpcworkers = 1
    blockTimer = 1000
    waitForChain = false
    reindex = true
    preventReattempts = true
    waitForChainDelay = 1
    indexingEnabled = true
    exitWhenCaughtUp = false
    osmosisRewardsOnly = false
    RewardIndexingEnabled = true
    Dry = false
```

**Comment by KyleMoser** [comment]
@danbryan Dave already said... it's the same as ticket 202

**Comment by danbryan** [comment]
Chatted about this in the `3/8/23` sprint, has not been resumed yet

**Comment by danbryan** [comment]
@pharr117 mind checking if this one can be closed out too

**Comment by pharr117** [comment]
Checked this one, it succeeded so I am closing this one.
