### ISSUE TITLE
Should MsgCreateValidator be ignored?

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#285]
I noticed this was in tx.go messageTypeIgnorer
https://github.com/DefiantLabs/cosmos-tax-cli-private/blob/main/core/tx.go#L93

When doing the command create-validator, there is a required min-self-delegation.
https://docs.cosmos.network/v0.46/modules/staking/03_messages.html#msgcreatevalidator

I would think this should be treated similar to MsgDelegate
https://github.com/DefiantLabs/cosmos-tax-cli-private/blob/0453d608b254d225e9ddaf22ac93c0f77d2071e2/cosmos/modules/staking/types.go#L24

What do you think?

**Comment by pharr117** [comment]
It definitely should not be ignored, I will add support for indexing it.

I have found a block on Osmosis containing this TX here: [8611192](https://www.mintscan.io/osmosis/blocks/8611192)

**Comment by pharr117** [comment]
I have just remembered why we ignored MsgCreateValidator originally:

All we care about in the staking module is reward receiving:

1. MsgDelegate will autowithdraw rewards when you delegate to a validator you are already delegated to, we capture those
2. MsgUndelegate same
3. MsgBeginRedelegate same

Since MsgCreateValidator does not auto-withdraw rewards, we ignored it originally.

**Comment by danbryan** [comment]
Doesn't MsgCreateValidator require a `--min-self-delegation` which i would think should be considered a withdraw, just like fees?

**Comment by pharr117** [comment]
Yes it does, but that is a Delegation action.

We ignore all other Delegation actions and only index reward distribution for delegations.

If we want to consider this a Withdraw, we should rethink our ignoring of MsgDelegate delegation tokens. Which would also mean we need to reindex all MsgDelegate etc... delegation messages

**Comment by danbryan** [comment]
Nope, i agree with you, delegation sounds right.

So it would be a withdraw for the fee, and then a deposit for the delegation.  Do we index it as a MsgDelegate, or as a MsgCreateValidator.  Im thinking in terms of the API, if someone wanted to see all their create/edit validator commands on a chain, would that be possible with our future api?

**Comment by danbryan** [comment]
@pharr117 can we close this?

**Comment by pharr117** [comment]
We are going to continue to ignore MsgCreateValidator due to our use-case as explained above (we skip Delegate actions).

If we change our minds in the behavior, we will need to support all the other delegation actions besides this one as well, and reindex them all.
