### ISSUE TITLE
FTL Error querying chain status

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#311]
Can someone review this line for me?
https://github.com/DefiantLabs/cosmos-tax-cli/blob/main/cmd/index.go#L78

I'm a little confused on the conditions we are checking. Do we need to check all 3 of these?

```
for (idxr.cfg.Base.WaitForChain || idxr.cfg.Base.ExitWhenCaughtUp) && chainCatchingUp && err == nil {
```

I would think if i set this flag
```
--base.wait-for-chain false
```

It should index an RPC server regardless of if it's in sync or not. However, it appears to give a FTL when hitting this RPC server.

```
curl -s http://35.247.5.192:26657/status | jq .result.sync_info.catching_up
true
```

should't it try to index, instead of saying
```
FTL. Error querying chain status
```

**Comment by pharr117** [comment]
Pasting the permalink for the line:

https://github.com/DefiantLabs/cosmos-tax-cli/blob/1ba057e7e663bfadbcec71830404655b0e09ea1c/cmd/index.go#L87

I am exploring these conditionals to figure out what needs to change. Its a bit convoluted.

**Comment by pharr117** [comment]
So for this line, I think we need to remove ExitWhenCaughtUp. This config value is used during indexing to say the app should exit when you have reached EndBlock in the config and has nothing to do with the waiting for chain check.

However, I have reproduced the "Error querying chain status" and this is a legitimate error. Its coming back when we hit the status endpoint and the response is an EOF. Not sure what the cause there is, looking into it now.

**Comment by danbryan** [comment]
I would like the following behavior:

I also don't think we need `wait-for-chain`.
I do think we should have something in place to handle the osmosis epoch downtimes.
I like the idea of exit when caught up, i think we should keep that option.

I'd be glad to chat about this if you like.

**Comment by pharr117** [comment]
We can definitely eliminate the wait-for-chain behavior. I think we originally intended it to be used for nodes that are behind, but it is not a requirement.

On my PR, the app still exits when caught up:
```
12:46AM INF Indexing 0 TXs from block 9
12:46AM INF Hit the last block we're allowed to index, exiting enqueue func.
12:46AM INF Indexing 0 TXs from block 10
12:46AM INF DB updates complete
```

We were just using the ExitWhenCaughtUp config option in the wrong location.
