### ISSUE TITLE
koinly, taxbit,cointracker errors

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#315]
On https://app.sycamore.tax/
if you put in this address
```
osmo1083svrca4t350mphfv9x45wq9asrs60cq5yv9n
```

and choose accointing, it works. But if you choose koinly, taxbit, or cointracker, then you get this error on the api.

```
{"level":"info","client_ip":"100.36.79.70","duration":"0","method":"OPTIONS","path":"/events.csv","status":"204","referrer":"https://app.sycamore.tax/","time":"2023-02-18T06:55:30Z"}
{"level":"info","time":"2023-02-18T06:55:30Z","message":"Start: <nil> End: <nil>\n"}
{"level":"error","error":"no parser for message type '/cosmos.gov.v1beta1.MsgSubmitProposal'","time":"2023-02-18T06:55:30Z","message":"Error processing taxable transaction."}
{"level":"error","time":"2023-02-18T06:55:30Z","message":"Error processing taxable transaction."}
{"level":"error","time":"2023-02-18T06:55:30Z","message":"Error getting rows for addresses: [osmo1083svrca4t350mphfv9x45wq9asrs60cq5yv9n]"}
{"level":"info","client_ip":"100.36.79.70","duration":"139","method":"POST","path":"/events.csv","status":"500","referrer":"https://app.sycamore.tax/","error":"Error getting rows for address","time":"2023-02-18T06:55:30Z"}
```

**Comment by danbryan** [comment]
reopening, why does this not happen on accointing?

```
{"level":"error","error":"no parser for message type '/cosmos.gov.v1beta1.MsgDeposit'","time":"2023-03-31T19:20:21Z","message":"Error processing taxable transaction."}              │
{"level":"error","time":"2023-03-31T19:20:21Z","message":"Error processing taxable transaction."}                                                                                     {"level":"error","time":"2023-03-31T19:20:21Z","message":"Error getting rows for addresses: [osmo1083svrca4t350mphfv9x45wq9asrs60cq5yv9n]"} 
```

**Comment by pharr117** [comment]
Here is the reason: We have to write out parsers for each of the supported formats. So when one format contains a parser for the TX in question, it won't error. But if the parser if missing for any of the others, it will error out.

This will keep popping up if devs don't add support for parsers to each of the supported formats.

I think what we can do to prevent this in the future is to do some pre-client-app run validation so:

1. Get full list of supported parsers for every output format
2. Check to see every format supports all expected formats
3. Hard crash with a "You missed one" error. Preventing the app from running will force devs to write support for all messages, and catch mistakes

I will work on adding support for the other formats though

**Comment by danbryan** [comment]
Thanks, and i like your idea.  Do you think that should be enforced in the code, or would that be a CI check?

**Comment by pharr117** [comment]
I can definitely enforce it in code if I do a slight rework of how the CSV parsers work, which won't take too much work. It also will make it easier to analyze and develop CSV parsers.

I think it would be better to enforce it in code. That way we can ensure that the CSV parsers are all equivalent before PRs get merged.
