### ISSUE TITLE
[Block: 8319511] ParseCosmosMessage failed for msg of type '/osmosis.gamm.v1beta1.MsgExitSwapShareAmountIn'. error="Type: /osmosis.gamm.v1beta1.MsgExitSwapShareAmountIn could not handle message log

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#333]
FTL Issue parsing a cosmos msg that we DO have a parser for! PLEASE INVESTIGATE

3:39PM INF Indexing 9 TXs from block 8319494.
3:39PM INF Indexing 8 TXs from block 8319491.
3:39PM ERR [Block: 8319511] ParseCosmosMessage failed for msg of type '/osmosis.gamm.v1beta1.MsgExitSwapShareAmountIn'. error="Type: /osmosis.gamm.v1beta1.MsgExitSwapShareAmountIn could not handle message log &{MessageIndex:0 Events:[{Type:burn Attributes:[{Key:burner Value:osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {Key:amount Value:42627363610490495gamm/pool/926}]} {Type:coin_received Attributes:[{Key:receiver Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {Key:amount Value:3795258ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F,40960uosmo} {Key:receiver Value:osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {Key:amount Value:42627363610490495gamm/pool/926} {Key:receiver Value:osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {Key:amount Value:40960uosmo} {Key:receiver Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {Key:amount Value:37572ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F}]} {Type:coin_spent Attributes:[{Key:spender Value:osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {Key:amount Value:3795258ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F,40960uosmo} {Key:spender Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {Key:amount Value:42627363610490495gamm/pool/926} {Key:spender Value:osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {Key:amount Value:42627363610490495gamm/pool/926} {Key:spender Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {Key:amount Value:40960uosmo} {Key:spender Value:osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {Key:amount Value:37572ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F}]} {Type:message Attributes:[{Key:action Value:/osmosis.gamm.v1beta1.MsgExitSwapShareAmountIn} {Key:sender Value:osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {Key:sender Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {Key:sender Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {Key:sender Value:osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {Key:module Value:gamm} {Key:sender Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u}]} {Type:pool_exited Attributes:[{Key:module Value:gamm} {Key:sender Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {Key:pool_id Value:926} {Key:tokens_out Value:3795258ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F,40960uosmo}]} {Type:token_swapped Attributes:[{Key:module Value:gamm} {Key:sender Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {Key:pool_id Value:926} {Key:tokens_in Value:40960uosmo} {Key:tokens_out Value:37572ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F}]} {Type:transfer Attributes:[{Key:recipient Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {Key:sender Value:osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {Key:amount Value:3795258ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F,40960uosmo} {Key:recipient Value:osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {Key:sender Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {Key:amount Value:42627363610490495gamm/pool/926} {Key:recipient Value:osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {Key:sender Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {Key:amount Value:40960uosmo} {Key:recipient Value:osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {Key:sender Value:osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {Key:amount Value:37572ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F}]}]}\n"
3:39PM ERR [Block: 8319511] ParseCosmosMessage failed for msg of type '/osmosis.gamm.v1beta1.MsgExitSwapShareAmountIn'.
3:39PM ERR &{0 [{burn [{burner osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {amount 42627363610490495gamm/pool/926}]} {coin_received [{receiver osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {amount 3795258ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F,40960uosmo} {receiver osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {amount 42627363610490495gamm/pool/926} {receiver osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {amount 40960uosmo} {receiver osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {amount 37572ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F}]} {coin_spent [{spender osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {amount 3795258ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F,40960uosmo} {spender osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {amount 42627363610490495gamm/pool/926} {spender osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {amount 42627363610490495gamm/pool/926} {spender osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {amount 40960uosmo} {spender osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {amount 37572ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F}]} {message [{action /osmosis.gamm.v1beta1.MsgExitSwapShareAmountIn} {sender osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {sender osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {sender osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {sender osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {module gamm} {sender osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u}]} {pool_exited [{module gamm} {sender osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {pool_id 926} {tokens_out 3795258ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F,40960uosmo}]} {token_swapped [{module gamm} {sender osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {pool_id 926} {tokens_in 40960uosmo} {tokens_out 37572ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F}]} {transfer [{recipient osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {sender osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {amount 3795258ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F,40960uosmo} {recipient osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {sender osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {amount 42627363610490495gamm/pool/926} {recipient osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {sender osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {amount 40960uosmo} {recipient osmo1wev8ptzj27aueu04wgvvl4gvurax6rj5p5lw4u} {sender osmo1qh460geara3hrqag82hth6qqkjj25gcj3v30wpfak5rjkff85t9qgk2s25} {amount 37572ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F}]}]}
3:39PM ERR 5DEACF0BD254B863928D09A43FC8F0E46C03295AAEEE6686EA833D443FA8B8D6
3:39PM FTL Issue parsing a cosmos msg that we DO have a parser for! PLEASE INVESTIGATE

**Comment by pharr117** [comment]
We treat MsgExitSwapShareAmountIn as a single coin event:

```
sf.TokenOut, err = sdk.ParseCoinNormalized(tokenOut)
``` 

line 709 of osmosis/modules/gamm/types.go

This message fails when it reaches the poolExitedEvent since the Coins received are:

`3795258ibc/8BE73A810E22F80E5E850531A688600D63AE7392E7C2770AE758CAA4FD921B7F,40960uosmo` for receiver `osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj`

Notice the double coin separated by a comma. Looks like this person received 2 types of tokens when executing this transaction

To fix:

The cosmos SDK provides a ParseCoinsNormalized method that can handle comma separated lists of coins, we should be using that instead (it works with a single coin too, so will not break in the opposite direction)
We will need to account for this up the chain of handlers. Since the receiver will have received 2 tokens, this (if I am still remembering the architecture of this app correctly) will be 2 taxable events

**Comment by pharr117** [comment]
The above is slightly incorrect, for [MsgExitSwapShareAmountIn](https://docs.osmosis.zone/osmosis-core/modules/gamm#exit-swap-share-amount-in), the Osmosis docs specify that you exit with one of the tokens in the pool.

I believe we may just be parsing the wrong event in the logs trying to get the amount that came out.
