### ISSUE TITLE
cosmoshub-4 - initial support.

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#334]
Error getting transactions by block height (8900000). Err: rpc error: code = InvalidArgument desc = failed to load state at height 8900000; version mismatch on immutable IAVL tree; version does not exist. Version has either been pruned, or is for a future block height (latest height: 14502063): invalid request. Will reattempt

![image](https://user-images.githubusercontent.com/807940/225952842-4b4f024a-a1f9-43c1-a23d-09dd1673f8fc.png)

it also failed with blocks from 1 month ago with the same error 
however it can do blocks from today

 Is it related to this maybe?
https://github.com/DefiantLabs/cosmos-tax-cli/blob/main/go.mod#L62

**Comment by pharr117** [comment]
After some initial testing where I tried to match the IAVL package version with the version specified on chain (working with Juno at the time), I believe this is a problem in specific Nodes.

According to the comment [here and further down on the issue](https://github.com/cosmos/cosmos-sdk/issues/14620#issuecomment-1416370915), this error can pop up in 1 of 2 ways:

1. Node pruning is on and configured in a certain way
2. Chain developers do not implement an upgrade correctly (see a Juno dev making comments on the same issue)

I am thinking that this is not an issue with our codebase, but can happen on specific nodes.

I will leave this open for further exploration for now, though.

**Comment by danbryan** [comment]
This has been resolved by adding this patch to cosmoshub node

https://github.com/Reecepbcups/cosmos-sdk/releases/tag/v0.45.15-archive.1
