### ISSUE TITLE
Block 8738544  - tx message could not be processed. CachedValue is not present. 

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#340]
ERR Block 8738544 failed. Reason: {unknown error} error="tx message could not be processed. CachedValue is not present. TX Hash: 69BB39D28B5EAFD83F94B799CABBE63F8D85DB77A39EFE004C641CBA01F8E99D, Msg type: /osmosis.poolmanager.v1beta1.MsgSwapExactAmountIn

**Comment by KyleMoser** [comment]
We're on 	`github.com/osmosis-labs/osmosis/v14 v14.0.1 ` which has `"/osmosis.gamm.v1beta1.MsgSwapExactAmountIn"` in the corresponding package (gamm). I'm guessing we just need to upgrade to Osmosis v15 in lens and obviously register `MsgSwapExactAmountIn` under the new type prefix `/osmosis.poolmanager.v1beta1.MsgSwapExactAmountIn ` (as well as keeping the old gamm one) in the cosmos-tax-cli. They probably still use the same parsing code.

BTW, if the Osmosis team removed `MsgSwapExactAmountIn` from gamm, we will also need to register an extra codec in Lens, following the pattern I established for `MsgCreatePool`. That way we will still be able to parse the old type and new one.

**Comment by danbryan** [comment]
@KyleMoser or @pharr117 I feel like there is a knowledge point here that I would like to be captured.  I'm not confident in my understanding of the significance of  being on `github.com/osmosis-labs/osmosis/v14 v14.0.1` ?  Are one of you willing to [create a github wiki in this repo](https://github.com/DefiantLabs/cosmos-tax-cli/wiki) on this subject? 

For example, questions that come to my mind are.

- Will we stay on this always?
- When would we want to update?
-  If we update , will the impact our ability to index old data?
-  is there anything significant i'm missing on this point?

**Comment by KyleMoser** [comment]
I think the information I posted in the comment captures everything
relevant to "how do I make it so a type is parseable" but if you want to
have a quick chat about it we can do that.

**Comment by danbryan** [comment]
Thanks @pharr117

**Comment by pharr117** [comment]
I have added a new branch to our Lens fork that I believe adds support for Osmosis v15.

Take a look here: [comparing current v0.0.11-dl to new v0.0.12-dl](https://github.com/DefiantLabs/lens/compare/v0.0.11-dl...DefiantLabs:lens:v0.0.12-dl?expand=1)

Pulling this branch into our go.mod fixes the error for this issue. I am not sure of all the implications of moving to v15, though. I am going to test on old blocks to make sure everything works the same.

```
10:41PM WRN [Block: 8738544] ParseCosmosMessage failed for msg of type '/osmosis.poolmanager.v1beta1.MsgSwapExactAmountIn'. We do not currently have a message handler for this message type
```

The rest of the transactions seem to work just fine.

Next step will be to add support for the new Pool Manager types.
