### ISSUE TITLE
Confusing Log: Task ended for DenomUpsertTask

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#341]
![image](https://user-images.githubusercontent.com/807940/227105747-8d02153d-00b3-44f9-902c-c79b47014a67.png)

I feel like we can make this more informative.  

- I think it's weird that it says the Task ended, but it never says the task started
- I don't think its clear what DenomUpsert means.  

I would like to have the following changes made.

1. Add INF log for `Updating Denom Metadata from {base.api}`
2. Change `Task ended for DenomUpsertTask` to `Denom Metadata Update Complete

**Comment by pharr117** [comment]
This one should be pretty easy.

The "task started" log is in the Debug output while "task ended" is in the Info output, thus you can't see the first.

Should be pretty simple to update the log output.

**Comment by danbryan** [comment]
They should probably both be at the same log level.  I'd say make them both INFO.
