### ISSUE TITLE
FTL ProcessRPCBlockByHeightTXs: TX cannot be parsed from block 327732. Err: unable to resolve type URL /osmosis.lockup.MsgUnlockTokens:

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#360]
FTL ProcessRPCBlockByHeightTXs: TX cannot be parsed from block 327732. Err: unable to resolve type URL /osmosis.lockup.MsgUnlockTokens:

![image](https://user-images.githubusercontent.com/807940/228313208-8aa50e61-594c-4fe8-a493-0bd923784493.png)

**Comment by danbryan** [comment]
this too

```
6:32PM FTL ProcessRPCBlockByHeightTXs: TX cannot be parsed from block 397747. Err: unable to resolve type URL /osmosis.lockup.MsgUnlockTokens
```

**Comment by danbryan** [comment]
and this.
```
FTL ProcessRPCBlockByHeightTXs: TX cannot be parsed from block 1116510. Err: unable to resolve type URL /osmosis.lockup.MsgUnlockTokens: tx parse error [osmosis-labs/cosmos-sdk@v0.45.1-0.20221118211718-545aed73e94e/x/auth/tx/decoder.go:42]
```

**Comment by pharr117** [comment]
This is another codec error for an old Omsosis type they removed. I will add it to our lens fork so we can process it successfully.
