### ISSUE TITLE
Check all parsers against juno validators

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#376]
Create a free account on:

- Koinly
- Accointing
- taxbit
- cointracker

Generate a report for 3 random validators from https://www.mintscan.io/juno/validators

Test each one in the above tax apps.

- Make sure the data loads (no error)
- and is identifiable. (coins show up in transactions, dates look reasonable, amounts look reasonable)

**Comment by pharr117** [comment]
First issue found, tracked here: https://github.com/DefiantLabs/cosmos-tax-cli/issues/386

**Comment by danbryan** [comment]
removed juno support, will consider in the future if funded
