### ISSUE TITLE
juno exponent bug?

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#396]
This should be  `100.000000` JUNO not `100,000,000.00000000` JUNO

[83d489354a5f350158f8a400dec18397183b546bcd595386c0ff00919457a92f](https://www.mintscan.io/juno/txs/83d489354a5f350158f8a400dec18397183b546bcd595386c0ff00919457a92f)

![image](https://user-images.githubusercontent.com/807940/235790533-a757a313-7c27-47eb-b15a-b26b71e21999.png)
[20230502175202-juno-events.csv](https://github.com/DefiantLabs/cosmos-tax-cli/files/11377970/20230502175202-juno-events.csv)

**Comment by pharr117** [comment]
I figured this one out:

1. We have a unique constraint on the DenomUnit model Name column - [source](https://github.com/DefiantLabs/cosmos-tax-cli/blob/2a5e58270a9388fb44d2a38e613b52ff3ecae1c0/db/models.go#L149)
2. Osmosis has a definition for "juno" exponent 6 for their IBC - [source](https://github.com/osmosis-labs/assetlists/blob/7dbb227377999b8e801605f1d1f249f33fc25595/osmosis-1/osmosis-1.assetlist.json#L790)
3. Juno also provides the same Name field - [source](https://github.com/cosmos/chain-registry/blob/4c2cee6a838cefc882b11a2a6c326abb1228388f/juno/assetlist.json#L13)
4. We ran Osmosis first, storing
    * Denom: `ID: 45,Base: ibc/46B44899322F3CD854D2D46DEEF881958467CDD4B3B10086DA49296BBED94BED,Name: Juno,Symbol: JUNO`
    * DenomUnit: `ID: 89, DenomID: 45, Exponent: 6, Name: juno`
5. We indexed Juno next, storing:
    * Denom: `ID: 27822,Base: ujuno, Name: Juno, Symbol: JUNO`
    * We then tried storing DenomUnit `juno` with exponent `6` and ran into the unique constraint, causing nothing to be inserted
6. Transactions with Denom ID 27822 now have no 6 exponent to calculate the symbol value on CSV export

The DenomUnit table is not terribly well thought out. I will need to rework how the table works.
