### ISSUE TITLE
Add configuration and workflow for indexing a list of specific, passed-in blocks

### ISSUE THREAD

**Issue by pharr117** [DefiantLabs/cosmos-tax-cli#404]
We currently have a few specific workflows for indexing:

1. Specified start block -> specified end block
    * If start block == -1, start from last indexed block
    * If end block == -1, index forever
2. Reindex failed blocks found in failed blocks table
    * Pull block heights from failed blocks table and reindex them

We should add a 3rd workflow for indexing a specific list of blocks. These should be passed in at runtime in some way, and the indexer should index these blocks only.

**Comment by danbryan** [comment]
This is a low priority for me, unless you feel it's necessary to be able to reindex the failed blocks.   I'm guessing not, since we have to do a full reindex anyways to get the IBC transactions.  Is this true? or do you think the failed blocks contain the IBC transfers?

**Comment by danbryan** [comment]
moving this to the backlog
