### ISSUE TITLE
Create Changelogs notes

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#418]
I would like to keep the habit of doing releases once per quarter to align with how we typically ask for funding.  

Can you create a detailed changelog, similar style to 
https://github.com/cosmos/relayer/releases/tag/v2.3.0 

with a list of the major milestones that has been done since 
https://github.com/DefiantLabs/cosmos-tax-cli/releases/tag/v0.3.0 

but not past 
https://github.com/DefiantLabs/cosmos-tax-cli/pull/368

We will do a 2nd release on June 30th for everything between 3/31/23 and 6/30/23

**Comment by danbryan** [comment]
@pharr117 , Can you do a partial Changelog for everything between 3/31/23 and 5/31/23 so i can send to Grant teams, we will still wait till 6/30/23 to cut release 1.2.0

**Comment by pharr117** [comment]
Marking this as done:

Changelog for release v1.1.0 went out on the release [here](https://github.com/DefiantLabs/cosmos-indexer/releases/tag/v1.1.0)

We are running with this current working Changelog tracking changes from the last commit in v1.1.0 (which ends at this commit [here](https://github.com/DefiantLabs/cosmos-indexer/commit/f0fb6f78a3cd6beaaebbcc29c37b41eb1b6b438a)), up until whatever makes it before 6/30.

Running changelog follows:

# Release v1.2.0 Highlights

* Indexing of blockchain-specific IBC Denom Trace Metadata: A new feature has been released that enables the indexing of blockchain-specific IBC Denom Trace Metadata. This allows for better tracking and analysis of inter-blockchain communication Denoms and use in downstream functionality.
* Indexer support for IBC MsgRecvPacket and successful MsgAcknowledgement: The indexer has been updated to include support for IBC MsgRecvPacket and successful MsgAcknowledgement transaction types. This enables better tracking and analysis of inter-blockchain communication and improves overall indexing functionality.
* Generalized BeginBlock and EndBlock event indexing: The indexer now has enhanced support for handling generalized BeginBlock and EndBlock block events. This includes specific support for Tendermint Liquidity module block events and Osmosis Incentives rewards. These improvements provide more comprehensive indexing capabilities.

# Changelog

This changelog highlights changes made to the Cosmos Indexer in Q2 of 2023 after release v1.1.0.

## Features

* Added support for the Osmosis Protorev module messages by bumping our support in Lens [#369](https://github.com/DefiantLabs/cosmos-indexer/pull/369)
* Released a feature to index blockchain specific IBC Denom Trace Metadata [#370](https://github.com/DefiantLabs/cosmos-indexer/pull/370)
* Added a Juno blockchain specific Denom Update task [#387](https://github.com/DefiantLabs/cosmos-indexer/pull/387)
* Released a new indexer feature to handle generalized BeginBlock ([#393](https://github.com/DefiantLabs/cosmos-indexer/pull/393)) and EndBlock ([#391](https://github.com/DefiantLabs/cosmos-indexer/pull/391)) block events
* Added EndBlock event indexing for Tendermint Liquidity module block events [#391](https://github.com/DefiantLabs/cosmos-indexer/pull/391)
* Added BeginBlock event indexing for Osmosis Incentives rewards [#393](https://github.com/DefiantLabs/cosmos-indexer/pull/393)
* Released a new indexer feature to handle indexing chain-specific denoms as its own command [#397](https://github.com/DefiantLabs/cosmos-indexer/pull/397)
* Added indexer support for IBC MsgRecvPacket [#399](https://github.com/DefiantLabs/cosmos-indexer/pull/399)
* Added indexer support for successful IBC MsgAcknowledgement [#420](https://github.com/DefiantLabs/cosmos-indexer/pull/420)


## Fixes

* Added missing support for MsgDeposit to all missing CSV output formats [#368](https://github.com/DefiantLabs/cosmos-indexer/pull/368)
* Fixed incorrect flag usage on indexer and added a chain status check retry on indexer startup [#311](https://github.com/DefiantLabs/cosmos-indexer/pull/375)
* Made improvements and fixed inconsistencies centered on failed block indexing handling [#388](https://github.com/DefiantLabs/cosmos-indexer/pull/388)
* Removed stray newline characters from all string functions that were polluting debug logs [#394](https://github.com/DefiantLabs/cosmos-indexer/pull/394)
* Fixed a large amount of general linter and stylechecker issues to clean the codebase up [#400](https://github.com/DefiantLabs/cosmos-indexer/pull/400), [#401](https://github.com/DefiantLabs/cosmos-indexer/pull/401), [#402](https://github.com/DefiantLabs/cosmos-indexer/pull/402), [#403](https://github.com/DefiantLabs/cosmos-indexer/pull/403), [#408](https://github.com/DefiantLabs/cosmos-indexer/pull/408)
* Added post-Denom Update command validation to ensure no orphaned denoms exist [#410](https://github.com/DefiantLabs/cosmos-indexer/pull/410)
* Removed all Fatal errors from functions run in the CSV generating API to prevent the API server from crashing [#411](https://github.com/DefiantLabs/cosmos-indexer/pull/411)
* Fixed a bug in using old version of NewCoin provided by alternate Cosmos SDK usage [#424](https://github.com/DefiantLabs/cosmos-indexer/pull/424), [#427](https://github.com/DefiantLabs/cosmos-indexer/pull/427)
* Fixed some error handling bugs in new IBC indexing functonality [#426](https://github.com/DefiantLabs/cosmos-indexer/pull/426), [#428](https://github.com/DefiantLabs/cosmos-indexer/pull/428)
