### ISSUE TITLE
Compare cosmos-indexer to graphprotocol/indexer 

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#430]
Do you mind looking into another indexer product.  https://github.com/graphprotocol/indexer  They specifically brought this one up and asked how our indexer is different from this one.  The readme makes it look like its focused on ethereum, but they are under the impression, also, I have first hand heard that they can operator on osmosis, and coming to other chains too.  So yeah, if you can look into, are they similar to us in that anyone can run their indexer software and index the same level of events we can on cosmos chain, specifically, the cosmoshub.  Also are their own pros to their solution, like do they maybe index non taxable data right now?  Or allow people to define custom DB models?

**Comment by pharr117** [comment]
See the wiki here: https://github.com/DefiantLabs/cosmos-indexer/wiki/Cosmos-Indexer-Ecosystem
