### ISSUE TITLE
cleanup context sensitive help

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#438]
Is it important to show all the global flags when someone is doing something like 

cosmos-indexer update-epochs --help  , they don't need to know stuff like --base.index-chain right?

**Comment by danbryan** [comment]
@pharr117 any thoughts on this one?

**Comment by pharr117** [comment]
This one will be tied up with #447. Since we got lazy and keep using the same setup command for each indexer command, they all require the same config values even when they do not use them. I will mark this one done when #447 is complete.

**Comment by pharr117** [comment]
Closed here: https://github.com/DefiantLabs/cosmos-tax-cli/pull/495
