### ISSUE TITLE
Add parser for Osmosis SplitRoute Exact Amount In poolmanager messages

### ISSUE THREAD

**Issue by pharr117** [DefiantLabs/cosmos-tax-cli#462]
In latest blocks, the poolmanager has a new message type available that is failing to be parsed.

We need to provide support for it:

https://github.com/osmosis-labs/osmosis/blob/46e6a0c2051a3a5ef8cdd4ecebfff7305b13ab98/proto/osmosis/poolmanager/v1beta1/tx.proto#L41

It works like the following:

1. Given a token in denom and a set of routes that end in the same denom
2. Swap the token in denom for the amount specified for each route
3. Get the single denom out that is at the end of each route

The message errors out if the ending route denoms do not match for every route

**Comment by danbryan** [comment]
using #466 instead
